server:
  port: 8080

spring:
  application:
    name: prescription-bot
  profiles:
    active: local

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/prescription_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  # Generic AI Config (Example uses OpenAI, but code should not rely on it)
  ai:
    openai:
      base-url: ${AI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/openai}
      api-key: ${API_KEY}
      chat:
        completions-path: /chat/completions
        options:
          model: ${AI_MODEL:gemini-3-flash-preview}
          # model: gemini-2.5-flash

  codec:
    max-in-memory-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: health,refresh
  endpoint:
    health:
      show-details: always

telegram:
  bot:
    token: ${TELEGRAM_BOT_TOKEN}
    username: ${TELEGRAM_BOT_USERNAME}

whatsapp:
  access-token: ${WHATSAPP_ACCESS_TOKEN:}
  phone-number-id: ${WHATSAPP_PHONE_NUMBER_ID:}
  verify-token: ${WHATSAPP_VERIFY_TOKEN:my_secure_token_123}

#aws:
#  s3:
#    region: ${AWS_REGION:us-east-1}
#    bucket-name: ${S3_BUCKET_NAME:prescription-bucket}
#    access-key: ${AWS_ACCESS_KEY_ID:demo}
#    secret-key: ${AWS_SECRET_ACCESS_KEY:demo}

aws:
  s3:
    region: ${S3_REGION}
    bucket-name: medical-prescriptions-bucket-demo
    access-key: ${ACCESS-KEY}
    secret-key: ${SECRET-KEY}


# Our custom AI config — controls runtime model switching & fallback
ai:
  config:
    active-provider: ${AI_PROVIDER:GEMINI}
    active-model: ${AI_MODEL:gemini-3-flash-preview}
    fallback-model: ${AI_FALLBACK_MODEL:gemini-2.5-flash}
    base-url: ${AI_BASE_URL:https://generativelanguage.googleapis.com/v1beta/openai}


